spring:
  datasource:
    baemin-expect:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: baemin-app
      jdbc-url: jdbc:mysql://ec2-3-35-47-230.ap-northeast-2.compute.amazonaws.com:3306/baemin-expect?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
      type: com.zaxxer.hikari.HikariDataSource
      password: a$rMSmSxpqE&
      pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
